// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowlistEntry(arg1) {
  return window['go']['main']['App']['AddAllowlistEntry'](arg1);
}

export function Calculate(arg1) {
  return window['go']['main']['App']['Calculate'](arg1);
}

export function GetAPIFingerprint() {
  return window['go']['main']['App']['GetAPIFingerprint']();
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetAPIStatus() {
  return window['go']['main']['App']['GetAPIStatus']();
}

export function GetAPIURL() {
  return window['go']['main']['App']['GetAPIURL']();
}

export function GetAllowlist() {
  return window['go']['main']['App']['GetAllowlist']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function RemoveAllowlistEntry(arg1) {
  return window['go']['main']['App']['RemoveAllowlistEntry'](arg1);
}

export function RotateAPIKey() {
  return window['go']['main']['App']['RotateAPIKey']();
}

export function SetAPIAutoStart(arg1) {
  return window['go']['main']['App']['SetAPIAutoStart'](arg1);
}

export function SetHTTPS(arg1) {
  return window['go']['main']['App']['SetHTTPS'](arg1);
}

export function SetOpacity(arg1) {
  return window['go']['main']['App']['SetOpacity'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ShuffleAPIPort() {
  return window['go']['main']['App']['ShuffleAPIPort']();
}

export function StartAPIServer() {
  return window['go']['main']['App']['StartAPIServer']();
}

export function StopAPIServer() {
  return window['go']['main']['App']['StopAPIServer']();
}

export function UIAck(arg1, arg2) {
  return window['go']['main']['App']['UIAck'](arg1, arg2);
}
