// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {settings} from '../models';

export function AddAllowlistEntry(arg1:string):Promise<Array<string>>;

export function Calculate(arg1:string):Promise<string>;

export function GetAPIFingerprint():Promise<string>;

export function GetAPIKey():Promise<string>;

export function GetAPIStatus():Promise<main.APIStatus>;

export function GetAPIURL():Promise<string>;

export function GetAllowlist():Promise<Array<string>>;

export function GetSettings():Promise<settings.Settings>;

export function GetVersion():Promise<string>;

export function RemoveAllowlistEntry(arg1:string):Promise<Array<string>>;

export function RotateAPIKey():Promise<string>;

export function SetAPIAutoStart(arg1:boolean):Promise<void>;

export function SetHTTPS(arg1:boolean):Promise<main.APIStatus>;

export function SetOpacity(arg1:number):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function ShuffleAPIPort():Promise<main.APIStatus>;

export function StartAPIServer():Promise<main.APIStatus>;

export function StopAPIServer():Promise<main.APIStatus>;

export function UIAck(arg1:string,arg2:string):Promise<void>;
